### ISSUE TITLE
Domain diagram

### ISSUE THREAD

**Issue by csorrike** [norbi0728/Rendszerfejlesztes#20]

**Comment by SoltiGabor** [comment]
Mik legyenek az osztályok? Nekem egyelőre csak ezek jutottak az eszembe:

User
Admin
Listing
Offer
Personal Information
Search Results
Sale

**Comment by norbi0728** [comment]
Money? Tárolná az értéket és a pénznemet.
Exchange? Tárolná a valutaárfolyamokat (USD, EUR, stb.) a forinthoz képest. Képes lenne a Money-t átváltani.

**Comment by norbi0728** [comment]
Item: A hírdetésben szereplő eladásra kínált tárgy, ami tartalmazhatna egy leírást, képeket, árat, kategóriát

PersonalizedOffers: értelemszerű. egybefogja azokat a  hirdetéseket, amiket megjelenítünk egy adott felhasználónak személyre szabottan

Marketplace: egybefogja a hirdetéseket, tartalmazza a PersonalizedOffers-t stb.

**Comment by SoltiGabor** [comment]
Personal Information
attribútumok:
name
address
phone
e-mail

Marketplace 1 -> * has Item

Listing
attribútumok:
title
description
fixed price
minimum bid

Listing 1..* -> 1 has Item
Listing 1..* -> 1 is published by User

Item
attribútumok:
name
description
picture

Listing 1 -> * has Offer
User 1 -> * has Offer

**Comment by SoltiGabor** [comment]
Marketplace 1 -> * provides Search Result

User 1 -> 1 has Personal Information

Design model:

Login Service
attr.: Account Information
-> authenticates Admin, User
