### ISSUE TITLE
Mik legyenek az árucikk fícsörök.

### ISSUE THREAD

**Issue by SoltiGabor** [norbi0728/Rendszerfejlesztes#29]
Azért nem tudok új listinget feltölteni, mert a FEATURES táblát fel kéne tölteni az összes megengedett feature nevével?

A felhasználónak egy adott listából kell majd választania, amikor megadja a cikk jellemzőit?

**Comment by norbi0728** [comment]
Igen, ide jöhetnének az ötletek a tárgyak tulajdonságaira, és akkor feltöltöm őket az adatbázisba. Amúgy ha jól emlékszem akkor igen, úgy kéne valahogy működnie, hogy a kliens lekéri a szervertől az összes lehetséges featuret és azok közül enged választani.

**Comment by norbi0728** [comment]
Manufacturer, Type,  Weight, Quality (new, like new, used, broken, ...), Display size, Warranty,  Power (battery, plug, ...).
Igazából elég sokmindent lehetne írni, ez szerintem úgy lenne szép, ha kiválasztja a felhasználó a termék kategóriát és annak megfelelően jelennének meg az elérhető tulajdonságok, mert nyilván ne kelljen már böngészni egy antik festmény feltöltésekor a kijelző méret meg a fogyasztás között... Ha ez nektek okés, akkor megírom rá az adatbázis oldali részt, kliens oldalról nem lesz változás.

**Comment by SoltiGabor** [comment]
Nem hiszem, hogy ez a hat kategória jól specifikálná a lehetséges jellemzők alhalmazait. Ahhoz túl tágak.

Szerintem az lenne a legjobb, ha a felhasználó szabadon beírhat string->string jellemzőket, és akkor  nem is korlátozza az, hogy mik vannak megadva, és nem is kell potenciálisan irreleváns kulcsok között böngésznie.

**Comment by norbi0728** [comment]
Okés nekem jó, úgy is van az adatbázisban már egy addFeature függvényt, azt akkor elérhetővé tesszük a kliens számára.

**Comment by norbi0728** [comment]
Ez viszont érinteni fog több model osztályt is, illetve az adatbázis sémáját is. Majd megírom mik a változások, amik esetleg érintenek titeket is.

**Comment by SoltiGabor** [comment]
Azt a kliens nem fogja tudni, hogy melyikek azok a feature-ök, amik még nem voltak, és "létre kell hozni". Az egy szerver-oldali implementációs dolog, hogy van egyáltalán olyan, hogy feature-t létrehozni.

**Comment by SoltiGabor** [comment]
Modell osztályt miért érint?

**Comment by norbi0728** [comment]
Mégse érint, csak rosszúl emlékeztem az Item osztály feature tárolására.
