### ISSUE TITLE
Összehasonlítás túl sok pipa

### ISSUE THREAD

**Issue by csorrike** [norbi0728/Rendszerfejlesztes#31]
Ha túl sok pipával kattintunk az összehasonlításra, akkor vagy vegye ki a nem összehasonlítottakat, vagy dobjon fel valami message box-ot, hogy túl sok kiválasztott. Vagy akár még többet is egymás mellé lehetne tenni, és oldalra lehtne görgetni.

**Comment by SoltiGabor** [comment]
Nincs túl sok, a legutóbb bejelölt kettőt hasonlítja össze.

**Comment by csorrike** [comment]
Viszont enged többet is bepipálni.

**Comment by SoltiGabor** [comment]
Ha lesz rá időm, foglalkozok ezzel is. Első ránézésre egy kicsit bonyolult.

**Comment by SoltiGabor** [comment]
Ehhez inkább nem nyúlnék hozzá.

**Comment by SoltiGabor** [comment]
Ha csak két dolgot lehetne bepipálni, akkor elveszthetné a felhasználó a fonalat, hogy hol hagyott valamit bepipálva a három különböző lista közül. Így viszont, hogy a legutóbbi két bepipálást hasonlítja össze, szerintem nagyon kényelmesen használható.

**Comment by csorrike** [comment]
Rendben. Akkor ez egy fícsör.
