### ISSUE TITLE
Licit kezelés

### ISSUE THREAD

**Issue by csorrike** [norbi0728/Rendszerfejlesztes#32]
Amikor valaki licitet tesz, egy megerősítő ablak feljöhetne, hogy a licit megtételével ennyi és ennyi összegre kötelezi önmagát. Jelenleg gyakorlatilag észre sem vettem, hogy licitáltam.

**Comment by SoltiGabor** [comment]
A BidLogic.addBid adja vissza a teljes szöveget, és akkor majd azt kiiratom. És akkor tényleg az íródik ki, ami tényleg jóvá lett írva a szerver által.

**Comment by csorrike** [comment]
Arra gondoltam, hogy mielőtt meghívod az addBid-et, egy megerősítő ablak ugorhatna fel, hogy tényleg licitálni szeretne-e ennyi megy ennyi pénz értékében.

**Comment by SoltiGabor** [comment]
Implementálva.
