### ISSUE TITLE
Ajánlás sor mérete

### ISSUE THREAD

**Issue by csorrike** [norbi0728/Rendszerfejlesztes#33]
Az ajánlás sor egy kicsivel kissebb mint amekkorák a listingeg, és ezért kicsit görgetni lehet, de az csak elrontja az összképet. Meg kéne növelni azt a területet akkorára, hogy beleférjen egy listing magassága.

**Comment by SoltiGabor** [comment]
A függőleges scrollbar-t nem sikerült eltöntetnem, de megcsináltam, hogy ne bújjon el az alja.

**Comment by norbi0728** [comment]
Összehekkeltem, már jó.
