### ISSUE TITLE
Legmagasabb licit mező

### ISSUE THREAD

**Issue by csorrike** [norbi0728/Rendszerfejlesztes#35]
Alapvetően ez a mező üresen jelenik meg. (Jobb lenne szerintem, ha alapból benne lenne a legmagasabb licict (ha még nem volt, akkor az, hogy még nem volt licit)). Továbbá ez egy írható, törölhető mező, ami gondolom nem a funkcionalitásának a része.

**Comment by SoltiGabor** [comment]
Ezt hol látod?

**Comment by SoltiGabor** [comment]
Ez megoldódott? Ez volt, amit a Norbi megcsinált?

**Comment by norbi0728** [comment]
Igen.
