### ISSUE TITLE
Licitlépcső

### ISSUE THREAD

**Issue by csorrike** [norbi0728/Rendszerfejlesztes#36]
A licitlépcső minden licitnél 0.0 (Nem tudom, hogy ez így van-e felvíve, vagy hiba).
Viszont így is növekszik a legmagasabb licit, ami kicsit gyanús.
/*És nem lehet átírni ezt. Alapvetően nem kell feltétlenül a licitlépcsőt betartani. Annál lehet magasabb értékkel licitálni,csak alacsonyabbal nem. Bár ez inkább továbbfejlesztési lehetőség, mert fix licitlépcsős licitálás is létezik.*/

**Comment by SoltiGabor** [comment]
Ez már megjavult?

**Comment by csorrike** [comment]
Igen
