### ISSUE TITLE
Hirdetés feladásakor visszajelzés

### ISSUE THREAD

**Issue by norbi0728** [norbi0728/Rendszerfejlesztes#38]
Meg kellene jeleníteni valami üzenetet a szerver válasza alapján, mert pl. 10-nél több hirdetés feladásakor a szerver leblokkol én meg nem tudtam, hogy miért nem tudok hozzáadni a kliensből új hírdetést. :D

**Comment by SoltiGabor** [comment]
Implementálva. Kiírja a szerver válaszát.
