### ISSUE TITLE
Kijelentkezés gomb

### ISSUE THREAD

**Issue by norbi0728** [norbi0728/Rendszerfejlesztes#39]

**Comment by norbi0728** [comment]
Implementálva, bár nem az igazi, mivel megmarad az előző user tartalma, ha olyan oldalon jelentkezünk ki, ahol nem frissül a tartalom bejelentkezés után (pl beállítás, saját hirdetések). De ez legyen az utolsó amivel bajlódunk.

**Comment by SoltiGabor** [comment]
Ez egy eléggé marginális use case implementálása. Hogy ha két különböző ember használja ugyanazt a gépet, akkor ne kelljen újraindítani a programot az átlépéshez.

Gondolom, meg lehetne csinálni, ha egyenként mindent reszetelget az ember valahogy, és újraindít minden inicializálást, de én most nem mernék ebbe belevágni.

**Comment by norbi0728** [comment]
Marad így, majd figyelek, ha esetleg demókor ki kell jelentkezni, hogy ne kényes oldalról csináljam. Viszont ha nem lenne ez a gomb és mondjuk egy másik felhasználóval kéne belépni, akkor ne kelljen már kilépni a programból azért, 1) mert hülyén néz ki, hogy azért ki kell lépni, 2) mert néha nem idul elsőre a program.

**Comment by SoltiGabor** [comment]
Nem kell kilépni, hanem lehet indítani újat. A licit állásának real-time frissülését úgy lehet demonstrálni, ha egyszerre van nyitva több felhasználóval a program.

Az, hogy nem indul elsőre, az szerintem nem hiba, de úgy tudod javítani, hogy kitörlöd a build könyvtáradat.

Vagy ha nem mered törölni, akkor kitörlöd a MarketClient\build\classes\java\main\marketplace\client könyvtárat.

Én tuti a közelébe se vinném az egérmutatómat a kilépés gombnak, szerintem undefined behavior kategória. De ahogy érzed.

**Comment by norbi0728** [comment]
Vettem.

**Comment by SoltiGabor** [comment]
Kijavítva.
