### ISSUE TITLE
személyre szabott ajánlatok

### ISSUE THREAD

**Issue by SoltiGabor** [norbi0728/Rendszerfejlesztes#40]
Nem tudom, pontosan mi a logikája a személyre szabott ajánlatoknak, de normális az, hogy a saját hirdetéseimet is ajánlja nekem, és egy hirdetést több példányban is?

**Comment by norbi0728** [comment]
Nem, arra illene rászürni.

**Comment by SoltiGabor** [comment]
Ezt megcsináljátok? Mert a bemutatón az nem biztos, hogy nagyon jól fog látszani, amit jól csinál ez a feature, az viszont nagyon feltűnő lesz, amit rosszul csinál.

**Comment by norbi0728** [comment]
Mindenképp.

**Comment by SoltiGabor** [comment]
Nekem még mindig ad saját hirdetéseket. Nálad jól működik?

**Comment by SoltiGabor** [comment]
Nekem egy csomó ismétlést meg sajátokat ad.
![Untitled](https://user-images.githubusercontent.com/47607557/82347389-d2c02100-99f7-11ea-8769-99fed485a540.jpg)

**Comment by csorrike** [comment]
Megnézitek most is? Én már nem látok se ismétlést, se sajátot.

**Comment by SoltiGabor** [comment]
Szerintem jónak tűnik.

**Comment by norbi0728** [comment]
Nekem az előbb adott ismétlődőt.

**Comment by norbi0728** [comment]
Működik.
