### ISSUE TITLE
Felhasználói statisztika frissítése

### ISSUE THREAD

**Issue by norbi0728** [norbi0728/Rendszerfejlesztes#42]
A szerver oldalon elérhető egy updateUserStatistic függvény a /updateStatistic úton, amit akkor kell használni, amikor valami Listinggel kapcsolatos dolog történik.  Radák jegyzetéből ezek a következők:  
   * Implemented events:
    * onList (when list by category),
    * onClick (when click on a listing),
    * onBid (when make a bid),
    * onAddListing (when create a listing),
    * onWin (when successfully wins an auction),
    * onDidNotGet (when made a bid on an auction but lost it)*/
Tehát ha ezek közül valamelyik megtörténik, akkor meg kell hívni a fenti függvényt, aminek kell az adott Listing kategóriája és az event leírása olyan formátumban, ahogy a leírásban szerepel, pl onList, onClick, stb..

**Comment by SoltiGabor** [comment]
Az nem baj, ha ezek közül nem lesz mindegyik? Pl. list by category téma nem lett implementálva.

**Comment by norbi0728** [comment]
Természetesen nem probléma.

**Comment by SoltiGabor** [comment]
Implementáltam.
