### ISSUE TITLE
Feature és Category módosítás nem megy

### ISSUE THREAD

**Issue by norbi0728** [norbi0728/Rendszerfejlesztes#44]

**Comment by SoltiGabor** [comment]
Database.java 427. sor: az item update-elése kicsit hiányos.

**Comment by norbi0728** [comment]
Category téma megoldódott.

**Comment by SoltiGabor** [comment]
Feature változtatás problémát nem sikerült reprodukálnom, átírtam a meglévő feature-t, írtam újat, mind rendesen update-elődött.

**Comment by SoltiGabor** [comment]
A feature törlés viszont nem megy.

**Comment by norbi0728** [comment]
Igen a feature törlés a probléma. Raktam be egy kiíratást arra az eventre, amikor megnyomjuk a feature line törlés "X" gombját, akárhányszor megnyomjuk kiíratom a features() által visszaadott Map méretét, és az változatlan annak ellenére, hogy maga a feature line eltűnik.

**Comment by norbi0728** [comment]
Kliens, ListingEditor 297. sorban van a probléma. A featureLines.remove() nem jó, mivel nem magát a line-t tárolja

**Comment by SoltiGabor** [comment]
Pontosan.

**Comment by SoltiGabor** [comment]
Javítás:

featureLines.remove(new Pair(propertyNameField, propertyValueField));

**Comment by norbi0728** [comment]
Nagyon szép.
