### ISSUE TITLE
Nyertes funkció

### ISSUE THREAD

**Issue by csorrike** [norbi0728/Rendszerfejlesztes#46]
Nyerés esetén rögzíteni a nyerést, update-elni a nyertes és a vesztesek statisztikáját, és kliens részen lekérdezhetővé tenni a nyertest. (Szerintem a lekérdezhetőséghez majd egy külön függvényt csinálok).

**Comment by SoltiGabor** [comment]
Ha ez csak a statisztika kedvéért volna, akkor lehet, hogy kihagynám, mert ezt nem igazán tudnánk látványosan demonstrálni a program látható működésével.

**Comment by csorrike** [comment]
Rákattintanánk az általunk licitált listában a hírdetésre, és feldobná, hogy nyertünk, avagy sem. De nem ragaszkodom hozzá.

**Comment by SoltiGabor** [comment]
Nem akarok már új fícsört beletenni, mert inkább a hibák lesznek a probléma, szerintem.
